apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wuar-demo-ntok
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wuar-demo-ntok
    app.kubernetes.io/part-of: wuar-demo
  name: wuar-demo-ntok
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: wuar-demo-ntok
status:
  loadBalancer: {}
